apiVersion: v1
kind: Service
metadata:
  name: photovault-api-service
  namespace: photovault
  labels:
    app: photovault-api
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.205
spec:
  selector:
    app: photovault-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer